### ISSUE TITLE
Remove CircuitPython Code from this repository

### ISSUE THREAD

**Issue by brentru** [adafruit/METROX-Examples-and-Project-Sketches#10]
CircuitPython code in this library is outdated.

Matching CircuitPython code for the Metro Experimenters Guide is located at https://github.com/adafruit/METROX-CircuitPython instead.

**Comment by brentru** [comment]
Resolved by https://github.com/adafruit/METROX-Examples-and-Project-Sketches/pull/11

**Comment by ladyada** [comment]
yayyy
