### ISSUE TITLE
CIRC06

### ISSUE THREAD

**Issue by microwattbott** [adafruit/METROX-Examples-and-Project-Sketches#2]
Is in need of update and modification:  (see below)

# CIRC06 - Music with Piezo 
# (Circuit Python)
# this circuit was designed for use with the Metro Express Explorers Guide on Learn.Adafruit.com 

# by Limor Fried/Ladyada and Asher Lieber for Adafruit Industries.             

# import required libraries
import digitalio
import pulseio
import board
import time
import simpleio

# d9
# a space represents a rest
notes = 'ccdcfeccdcgf ' 
beats = [ 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 4]
#notes = 'ccggaagffeeddc ' # a space represents a rest
#beats = [ 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 4 ]
#tones = {'c': 261.625,
         #'d': 293.665,
         #'e': 329.63,
         #'f': 349.23,
         #'g': 391.995,
         #'a': 440,
         #'b': 493.885,
         #'C': 523.25}
tones = {'c': 261,        #  simpleio.tone() needs an 
         'd': 294,            #  integer for the second arg.
         'e': 330,            #  the note's frequency.
         'f': 349,
         'g': 392,
         'a': 440,
         'b': 494,
         'C': 523}
# bpm
tempo = 450

# play the notes!
for i in range(len(notes)):
    tempodelay = 60 / tempo

    note = notes[i]
    duration = (beats[i] *tempodelay)
    print(note, end='')
    if note == ' ':
        time.sleep(duration)
    else:
        simpleio.tone(board.D9, tones[note], duration)
    time.sleep(tempodelay/2)

**Comment by brentru** [comment]
Thanks for the feedback! Fixed TypeError with floats in CIRC06, tested working on my board.
